# Site settings
title: here's to the little things
email: christopherazar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  to the designers, the makers, the hustlers: the world is yours.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://christopherazar.com" # the base hostname & protocol for your site
twitter_username: reptarazar
github_username:  reptarazar

# Build settings
markdown: kramdown
