# Site settings
title: Christopher Azar
email: christopherazar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Christopher is a product designer at SocialCode and lives in San Francisco.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://christopherazar.com" # the base hostname & protocol for your site
twitter_username: reptarazar
github_username:  reptarazar

# Build settings
markdown: kramdown
